version: '3.8'
services:
  mariadb:
    image: mariadb
    restart: on-failure
    environment:
      MARIADB_ROOT_PASSWORD: mariadb
      MARIADB_DATABASE: mariadb
      MARIADB_USER: mariadb
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8000:8080
    depends_on:
      - mariadb
